[package]
name = "supersonic-tx"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
name = "supersonic_tx"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang.workspace = true
solana-program.workspace = true

[dev-dependencies]
solana-program-test = "~1.18"
solana-sdk.workspace = true
tokio.workspace = true
supersonic-tx-core = { path = "../../crates/supersonic-tx-core" }
