[package]
name = "supersonic-tx-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
solana-sdk.workspace = true
solana-program.workspace = true
serde.workspace = true
rand.workspace = true
thiserror.workspace = true
